# Generated by Django 3.1.6 on 2021-02-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Субъект РФ')),
            ],
            options={
                'verbose_name': 'Регионы',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='MandatBasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(default='', max_length=30, verbose_name='Тип мандата')),
            ],
            options={
                'verbose_name': 'Мандат',
                'verbose_name_plural': 'Мандат',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_heading', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Закон',
                'verbose_name_plural': 'Законы',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forseti.post')),
            ],
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='ФИО')),
                ('region', models.CharField(blank=True, default='', max_length=400, verbose_name='Регион')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('image', models.ImageField(upload_to='deputy/', verbose_name='Изображение')),
                ('electoral_district', models.CharField(blank=True, default='', max_length=20, verbose_name='Избирательный округ')),
                ('current_squad', models.BooleanField(default=True, verbose_name='Действующий состав')),
                ('mandat_basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forseti.mandatbasis', verbose_name='мандат')),
                ('party_fraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forseti.partyfraction', verbose_name='фракция')),
            ],
            options={
                'verbose_name': 'Депутат',
                'verbose_name_plural': 'Депутаты',
            },
        ),
    ]
