# Generated by Django 3.1.6 on 2021-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0002_deputy_federalregion_like_mandatbasis_post_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='rule_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер законопроекта'),
        ),
    ]
