# Generated by Django 3.1.6 on 2021-02-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0003_rules_rule_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
