# Generated by Django 3.1.6 on 2021-03-01 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0007_auto_20210301_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='initialization_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата внесения на рассмотрение'),
        ),
        migrations.AddField(
            model_name='rules',
            name='rule_link',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на страницу на сайте ГД'),
        ),
        migrations.AddField(
            model_name='rules',
            name='rule_tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='rules',
            name='vote_abstained',
            field=models.TextField(default='', max_length=10000, verbose_name='Воздержались'),
        ),
        migrations.AddField(
            model_name='rules',
            name='vote_no',
            field=models.TextField(default='', max_length=10000, verbose_name='Против'),
        ),
        migrations.AddField(
            model_name='rules',
            name='vote_not_vote',
            field=models.TextField(default='', max_length=10000, verbose_name='Не голосовали'),
        ),
        migrations.AddField(
            model_name='rules',
            name='vote_yes',
            field=models.TextField(default='', max_length=10000, verbose_name='За'),
        ),
        migrations.AddField(
            model_name='rules',
            name='voting_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата голосования'),
        ),
    ]
