# Generated by Django 3.1.6 on 2021-03-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0008_auto_20210301_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='title',
            field=models.TextField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
