# Generated by Django 3.1.6 on 2021-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0009_auto_20210301_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='author',
            field=models.ManyToManyField(blank=True, limit_choices_to={'current_squad': True}, related_name='rule_author', to='forseti.Deputy', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='author_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Другие авторы'),
        ),
    ]
