# Generated by Django 3.1.6 on 2021-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0010_auto_20210301_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='vote_abstained',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Воздержались'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='vote_no',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Против'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='vote_not_vote',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Не голосовали'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='vote_yes',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='За'),
        ),
    ]
