# Generated by Django 3.1.6 on 2021-03-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0012_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
