# Generated by Django 3.1.6 on 2021-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0013_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
