# Generated by Django 3.1.6 on 2021-03-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0014_rules_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
