# Generated by Django 3.1.6 on 2021-03-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0015_rules_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
    ]
