# Generated by Django 3.1.6 on 2021-03-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forseti', '0017_prefer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPrefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forseti.rules')),
            ],
            options={
                'verbose_name': 'Дизлайки',
                'verbose_name_plural': 'Дизлайки',
            },
        ),
    ]
