# Generated by Django 3.1.6 on 2021-03-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0019_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
