# Generated by Django 3.1.6 on 2021-03-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0020_comments_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='likes',
        ),
    ]
