# Generated by Django 3.1.6 on 2021-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0021_auto_20210322_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='num_abstained',
            field=models.IntegerField(default=0, verbose_name='Воздержались'),
        ),
        migrations.AddField(
            model_name='rules',
            name='num_no',
            field=models.IntegerField(default=0, verbose_name='Против'),
        ),
        migrations.AddField(
            model_name='rules',
            name='num_not_vote',
            field=models.IntegerField(default=0, verbose_name='Не голосовали'),
        ),
        migrations.AddField(
            model_name='rules',
            name='num_yes',
            field=models.IntegerField(default=0, verbose_name='За'),
        ),
    ]
