# Generated by Django 3.1.6 on 2021-03-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0023_auto_20210322_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='num_yes',
            field=models.IntegerField(blank=True, verbose_name='За'),
        ),
    ]
