# Generated by Django 3.1.6 on 2021-03-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0024_auto_20210322_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
