# Generated by Django 3.1.6 on 2021-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0026_deputytest_finaltable_rowvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='vote_result',
            field=models.CharField(max_length=20, verbose_name='Результат голосования'),
        ),
    ]
