# Generated by Django 3.1.6 on 2021-03-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0028_auto_20210324_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='num_abstained',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='num_no',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='num_not_vote',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='num_yes',
        ),
    ]
