# Generated by Django 3.1.6 on 2021-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0029_auto_20210324_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='populated',
            field=models.BooleanField(default=False, verbose_name='Заполнение таблицы FinalTable'),
        ),
    ]
