# Generated by Django 3.1.6 on 2021-03-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0033_auto_20210326_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputy',
            name='party_fraction',
            field=models.CharField(choices=[('Единая Россия', 'Единая Россия'), ('КПРФ', 'КПРФ'), ('Справедливая Россия', 'Справедливая Россия'), ('ЛДПР', 'ЛДПР'), ('Вне фракций', 'Вне фракций')], default='p', max_length=50, verbose_name='Фракция'),
        ),
    ]
