# Generated by Django 3.1.6 on 2021-03-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0036_auto_20210326_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finaltable',
            options={'verbose_name': 'Голосования', 'verbose_name_plural': 'Голосования'},
        ),
    ]
