# Generated by Django 3.1.6 on 2021-03-29 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0037_auto_20210326_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='voted',
            field=models.BooleanField(default=False, verbose_name='Проголосовали'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='initialization_date',
            field=models.DateField(default=datetime.date.today, verbose_name='На рассмотрение'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='populated',
            field=models.BooleanField(default=False, verbose_name='FinalTable'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rule_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер закона'),
        ),
    ]
