# Generated by Django 3.1.6 on 2021-04-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0039_voxpopuli'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeputyTest',
        ),
        migrations.AlterModelOptions(
            name='voxpopuli',
            options={'verbose_name': 'Народное голосование', 'verbose_name_plural': 'Народное голосование'},
        ),
    ]
