# Generated by Django 3.1.6 on 2021-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0041_remove_rules_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Номер закона'),
        ),
    ]
