# Generated by Django 3.1.6 on 2021-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0046_auto_20210428_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='description',
            field=models.TextField(default='', max_length=50000, verbose_name='Описание'),
        ),
    ]
