# Generated by Django 3.1.6 on 2021-04-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0047_auto_20210428_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='status_quo',
            field=models.CharField(blank=True, choices=[('Рассмотрение', 'Рассмотрение'), ('Архив', 'Архив'), ('Отзыв', 'Отзыв')], default='Рассмотрение', max_length=20, verbose_name='Статус'),
        ),
    ]
