# Generated by Django 3.1.6 on 2021-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0049_auto_20210429_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='status_quo',
        ),
        migrations.AddField(
            model_name='rules',
            name='rejection',
            field=models.BooleanField(default=False, verbose_name='Отклонён'),
        ),
    ]
