# Generated by Django 3.1.6 on 2021-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0051_auto_20210429_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='voting_date',
            field=models.DateField(default='', verbose_name='Дата голосования'),
        ),
    ]
