# Generated by Django 3.1.6 on 2021-04-29 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0054_auto_20210429_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='initialization_date',
            field=models.DateField(default=None, verbose_name='На рассмотрении с'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='voting_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата голосования'),
        ),
    ]
