# Generated by Django 3.1.6 on 2021-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0057_auto_20210429_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='branch',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='Отрасль законодательства'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='description',
            field=models.TextField(default='', max_length=50000, verbose_name='Описание'),
        ),
    ]
