# Generated by Django 3.1.6 on 2021-04-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0059_auto_20210429_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='yet_voted',
            field=models.BooleanField(default=False, verbose_name='Уже проголосовали?'),
        ),
    ]
