# Generated by Django 3.1.6 on 2021-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0060_rules_yet_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='proved_rule',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
