# Generated by Django 3.1.6 on 2021-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0061_rules_proved_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='vote_no',
            field=models.TextField(blank=True, default='', max_length=15000, verbose_name='Против'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='vote_yes',
            field=models.TextField(blank=True, default='', max_length=15000, verbose_name='За'),
        ),
    ]
