# Generated by Django 3.1.6 on 2021-04-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0062_auto_20210429_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='proved_rule',
        ),
    ]
