# Generated by Django 3.1.6 on 2021-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0063_remove_rules_proved_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='title',
            field=models.TextField(max_length=700, verbose_name='Заголовок'),
        ),
    ]
