# Generated by Django 3.1.6 on 2021-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0064_auto_20210430_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Отрасль законодательства'),
        ),
    ]
