# Generated by Django 3.1.6 on 2021-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0065_auto_20210503_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule_link',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на страницу на сайте ГД'),
        ),
    ]
