# Generated by Django 3.1.6 on 2021-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0066_auto_20210504_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputy',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='ФИО'),
        ),
    ]
