# Generated by Django 3.1.6 on 2021-05-27 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0070_auto_20210519_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRulesForVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(default='', max_length=20, verbose_name='Номер закона')),
                ('last_check', models.DateField(default=datetime.date.today, verbose_name='Дата последней проверки')),
            ],
        ),
    ]
