# Generated by Django 3.1.6 on 2021-05-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0071_checkrulesforvoting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkrulesforvoting',
            options={'verbose_name': 'Проверка голосования', 'verbose_name_plural': 'Проверка голосования'},
        ),
        migrations.AddField(
            model_name='checkrulesforvoting',
            name='result',
            field=models.BooleanField(default=False, verbose_name='Результат'),
        ),
    ]
