# Generated by Django 3.1.6 on 2021-05-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0073_checkrulesforvoting_rule_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkrulesforvoting',
            old_name='rule',
            new_name='rule_number',
        ),
        migrations.RemoveField(
            model_name='checkrulesforvoting',
            name='result',
        ),
    ]
