# Generated by Django 3.1.6 on 2021-05-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0074_auto_20210527_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowManyRulesChecked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(default='', verbose_name='Дата проверки')),
            ],
            options={
                'verbose_name': 'Количество проверок',
                'verbose_name_plural': 'Количество проверок',
            },
        ),
    ]
