# Generated by Django 3.1.6 on 2021-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0075_howmanyruleschecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='set_start_period',
            field=models.BooleanField(default=True, verbose_name='Добавлен закон в таблицу CheckRulesForVoting?'),
        ),
    ]
