# Generated by Django 3.1.6 on 2021-06-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0076_rules_set_start_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='set_start_period',
            field=models.BooleanField(default=False, verbose_name='Добавлен закон в таблицу CheckRulesForVoting?'),
        ),
    ]
