# Generated by Django 3.1.6 on 2021-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0079_auto_20210602_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RowVote',
        ),
        migrations.AddField(
            model_name='rules',
            name='consumer',
            field=models.CharField(default='Неизвестен', max_length=400, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='populated',
            field=models.BooleanField(default=False, verbose_name='Д зап'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='populi_voted',
            field=models.BooleanField(default=False, verbose_name='Народ'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='result_deputy_vote',
            field=models.CharField(default='', max_length=10, verbose_name='Рез депутатов'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='result_populi_vote',
            field=models.CharField(default='', max_length=10, verbose_name='Рез народа'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='voted',
            field=models.BooleanField(default=False, verbose_name='Депутаты'),
        ),
    ]
