# Generated by Django 3.1.6 on 2021-06-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0080_auto_20210607_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notprefer',
            options={'verbose_name': 'Бесполезность', 'verbose_name_plural': 'Бесполезность'},
        ),
        migrations.AlterModelOptions(
            name='prefer',
            options={'verbose_name': 'Нужность', 'verbose_name_plural': 'Нужность'},
        ),
        migrations.AlterField(
            model_name='prefer',
            name='person',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='prefer',
            name='rule',
            field=models.CharField(max_length=15, verbose_name='Закон'),
        ),
    ]
