# Generated by Django 3.1.6 on 2021-06-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0081_auto_20210609_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notprefer',
            name='person',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='notprefer',
            name='rule',
            field=models.CharField(max_length=15, verbose_name='Закон'),
        ),
    ]
