# Generated by Django 3.1.6 on 2021-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0083_rules_constitutional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='vote_not_vote',
            field=models.TextField(blank=True, default='', max_length=15000, verbose_name='Не голосовали'),
        ),
    ]
