# Generated by Django 3.1.6 on 2021-06-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0084_auto_20210611_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
