# Generated by Django 3.1.6 on 2021-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0085_remove_comments_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskForDeputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_author', models.CharField(max_length=50, verbose_name='Автор')),
                ('task_text', models.CharField(max_length=10000, verbose_name='Поручение')),
                ('task_date', models.DateField(default='', verbose_name='Дата регистрации поручения')),
                ('task_rating', models.IntegerField(default=0, verbose_name='Рейтинг поручения')),
                ('deputy_name', models.CharField(max_length=50, verbose_name='Для депутата')),
            ],
            options={
                'verbose_name': 'Поручения',
                'verbose_name_plural': 'Поручения',
            },
        ),
    ]
