# Generated by Django 3.1.6 on 2021-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0086_taskfordeputy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0, verbose_name='Id поручения')),
                ('name', models.CharField(max_length=50, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг поручений',
                'verbose_name_plural': 'Рейтинг поручений',
            },
        ),
    ]
