# Generated by Django 3.1.6 on 2021-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0087_tasksrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='populi_voted',
            field=models.BooleanField(default=False, verbose_name='Н зап'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='voting_date',
            field=models.DateField(default=None, verbose_name='Дата голосования'),
        ),
    ]
