# Generated by Django 3.1.6 on 2021-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0088_auto_20210624_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='voting_date',
            field=models.DateField(default='', verbose_name='Дата голосования'),
        ),
    ]
