# Generated by Django 3.1.6 on 2021-06-24 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forseti', '0089_auto_20210624_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='voting_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата голосования'),
        ),
    ]
